### ISSUE TITLE
Dynamic search function

### ISSUE THREAD

**Issue by ariebrainware** [ariebrainware/javascript-challenge2#1]
I want to make dynamic search engine which can search any data and ignoring case sensitive from the input, i've done some experiment like down below but still doesnt work. The output is just the first index from data ```array```
https://github.com/ariebrainware/javascript-challenge2/blob/a137b4551747f5286710abf16fc2fa3efdb8f599/index.js#L42-L52

I implement this with [array.find()](https://devdocs.io/javascript/global_objects/array/find) but i dont get the point from [devdocs](https://devdocs.io) example.

Maybe you have another algorithm to make this searchEngine work. 

@mhaidarh @michaeltamsil

**Comment by michaeltamsil** [comment]
first: names array names must be loop
inside loop there's checking whether is match or not regarding case sensitive

this is example i modified

https://jsbin.com/jihoqiy/edit?html,console,output

you can try by clicking `run with js` button

**Comment by mhaidarhanif** [comment]
Use `filter` method, it simply works.

```js
const found = names.filter(name => {
	return name.toLowerCase().includes(keyword.toLowerCase());
});
```
